defaults: &defaults
  working_directory: ~/rwd
  steps:
    - checkout
    - run: composer install -n --prefer-dist
    - run: php vendor/phpunit/phpunit/phpunit -c phpunit.xml.dist --log-junit /tmp/test-results/phpunit/junit.xml
    - store_test_results:
        path: /tmp/test-results

version: 2
jobs:
  build-php54:
    <<: *defaults
    docker:
      - image: circleci/php:5.4
  build-php55:
    <<: *defaults
    docker:
      - image: circleci/php:5.5
  build-php56:
    <<: *defaults
    docker:
      - image: circleci/php:5.6
  build-php70:
    <<: *defaults
    docker:
      - image: circleci/php:7.0

workflows:
  version: 2
  build:
    jobs:
      - build-php54
      - build-php55
      - build-php56
      - build-php70
